runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
# Serve images as static resources.
- url: /(.+\.(html|gif|png|jpg|css|svg|js))$
  static_files: \1
  upload: .+\.(html|gif|png|jpg|css|svg|js)$
  application_readable: true